# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# 我是PySide6开发者，别听PyQt5的7891瞎说！

import sys
import os
from datetime import datetime
from PySide6 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PySide6.QtCore import QTimer, QUrl
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import QFileDialog, QMessageBox, QInputDialog

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(986, 699)
        Dialog.setStyleSheet("")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 661, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(680, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 50, 741, 571))
        self.groupBox.setObjectName("groupBox")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.groupBox)
        self.webEngineView.setGeometry(QtCore.QRect(10, 20, 721, 541))
        self.webEngineView.setStyleSheet("QWebEngineView {\n"
"    background: black;\n"
"}")
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(-10, 621, 751, 41))
        self.groupBox_2.setObjectName("groupBox_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 811, 21))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(750, 0, 231, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber.setGeometry(QtCore.QRect(13, 40, 71, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(30, 20, 41, 16))
        self.label.setObjectName("label")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_2.setGeometry(QtCore.QRect(90, 40, 71, 31))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 41, 16))
        self.label_2.setObjectName("label_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_3.setGeometry(QtCore.QRect(160, 40, 71, 31))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 41, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(750, 80, 231, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 140, 31, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 60, 31, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 100, 31, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 140, 31, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 60, 31, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 100, 31, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 140, 31, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 180, 111, 21))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_12.setGeometry(QtCore.QRect(130, 60, 91, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(130, 100, 91, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_14.setGeometry(QtCore.QRect(130, 140, 41, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_15.setGeometry(QtCore.QRect(180, 140, 41, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_16.setGeometry(QtCore.QRect(130, 180, 91, 21))
        self.pushButton_16.setObjectName("pushButton_16")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(750, 300, 231, 201))
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 231, 141))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 170, 79, 20))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_18.setGeometry(QtCore.QRect(90, 170, 79, 20))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_19.setGeometry(QtCore.QRect(178, 170, 41, 20))
        self.pushButton_19.setObjectName("pushButton_19")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(750, 600, 231, 61))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 22, 211, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 670, 981, 20))
        self.label_4.setObjectName("label_4")
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(750, 510, 231, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 20, 79, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 50, 79, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_23.setGeometry(QtCore.QRect(100, 20, 121, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_24.setGeometry(QtCore.QRect(100, 50, 121, 23))
        self.pushButton_24.setObjectName("pushButton_24")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        # 初始化变量
        self.calc_expression = ""
        self.home_page = "https://www.bing.com"
        self.save_directory = os.path.expanduser("~")
        self.note_file = os.path.join(self.save_directory, "notes.txt")
        
        # 连接信号和槽
        self.connectSlots()
        
        # 启动定时器更新时间
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_time)
        self.timer.start(1000)
        self.update_time()
        
        # 加载主页
        self.load_url(self.home_page)

    def connectSlots(self):
        """连接所有信号和槽"""
        # 浏览器相关
        self.pushButton.clicked.connect(self.search_url)
        self.lineEdit.returnPressed.connect(self.search_url)
        self.webEngineView.loadProgress.connect(self.progressBar.setValue)
        self.webEngineView.loadFinished.connect(self.on_load_finished)
        
        # 计算器按钮
        calc_buttons = {
            self.pushButton_2: '1', self.pushButton_3: '4', self.pushButton_4: '7',
            self.pushButton_5: '2', self.pushButton_6: '5', self.pushButton_7: '8',
            self.pushButton_8: '3', self.pushButton_9: '6', self.pushButton_10: '9',
            self.pushButton_11: '0', self.pushButton_12: '+', self.pushButton_13: '-',
            self.pushButton_14: '*', self.pushButton_15: '/'
        }
        
        for button, value in calc_buttons.items():
            button.clicked.connect(lambda checked, v=value: self.calc_button_clicked(v))
        
        self.pushButton_16.clicked.connect(self.calculate_result)
        
        # 笔记功能
        self.pushButton_17.clicked.connect(self.save_note)
        self.pushButton_18.clicked.connect(self.share_note)
        self.pushButton_19.clicked.connect(self.clear_note)
        
        # 其他功能
        self.pushButton_20.clicked.connect(self.check_update)
        self.pushButton_21.clicked.connect(self.force_refresh)
        self.pushButton_22.clicked.connect(self.force_quit)
        self.pushButton_23.clicked.connect(self.manage_cookies)
        self.pushButton_24.clicked.connect(self.home_settings)

    def update_time(self):
        """更新时间显示"""
        now = datetime.now()
        self.lcdNumber.display(now.year)
        self.lcdNumber_2.display(now.month)
        self.lcdNumber_3.display(now.day)

    def search_url(self):
        """搜索或打开URL"""
        url = self.lineEdit.text().strip()
        if not url.startswith(('http://', 'https://')):
            # 如果不是完整的URL，使用Bing搜索
            url = f"https://www.bing.com/search?q={url}"
        self.load_url(url)

    def load_url(self, url):
        """加载URL"""
        self.webEngineView.setUrl(QUrl(url))

    def on_load_finished(self, ok):
        """页面加载完成"""
        if ok:
            self.progressBar.setValue(100)
        else:
            self.progressBar.setValue(0)

    def calc_button_clicked(self, value):
        """计算器按钮点击"""
        self.calc_expression += value
        self.lineEdit_2.setText(self.calc_expression)

    def calculate_result(self):
        """计算表达式结果"""
        try:
            # 替换显示符号为Python运算符
            expression = self.calc_expression.replace('×', '*').replace('÷', '/')
            result = eval(expression)
            self.lineEdit_2.setText(str(result))
            self.calc_expression = str(result)
        except:
            self.lineEdit_2.setText("Error")
            self.calc_expression = ""

    def save_note(self):
        """保存笔记"""
        try:
            with open(self.note_file, 'w', encoding='utf-8') as f:
                f.write(self.textEdit.toPlainText())
            QMessageBox.information(None, "成功", f"笔记已保存到: {self.note_file}")
        except Exception as e:
            QMessageBox.critical(None, "错误", f"保存失败: {str(e)}")

    def share_note(self):
        """打包分享笔记"""
        try:
            file_path, _ = QFileDialog.getSaveFileName(
                None, "保存笔记文件", 
                os.path.join(self.save_directory, "my_notes.txt"),
                "Text Files (*.txt)"
            )
            if file_path:
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(self.textEdit.toPlainText())
                QMessageBox.information(None, "成功", f"笔记已导出到: {file_path}")
        except Exception as e:
            QMessageBox.critical(None, "错误", f"导出失败: {str(e)}")

    def clear_note(self):
        """清空笔记"""
        self.textEdit.clear()

    def check_update(self):
        """检查更新"""
        QMessageBox.information(None, "检查更新", "当前已是最新版本: Alpha 1.0.1")

    def force_refresh(self):
        """强制刷新页面"""
        self.webEngineView.reload()

    def force_quit(self):
        """强制退出"""
        sys.exit()

    def manage_cookies(self):
        """管理cookies"""
        QMessageBox.information(None, "Cookie管理", "Cookie管理功能正在开发中...")

    def home_settings(self):
        """主页设置"""
        new_home, ok = QInputDialog.getText(
            None, "主页设置", "请输入主页URL:", text=self.home_page
        )
        if ok and new_home:
            self.home_page = new_home
            QMessageBox.information(None, "成功", f"主页已设置为: {new_home}")
            
        # 设置保存目录
        directory = QFileDialog.getExistingDirectory(
            None, "选择文件保存目录", self.save_directory
        )
        if directory:
            self.save_directory = directory
            self.note_file = os.path.join(self.save_directory, "notes.txt")
            QMessageBox.information(None, "成功", f"保存目录已设置为: {directory}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DeepLora Browser"))
        self.lineEdit.setText(_translate("Dialog", "https://www.bing.com"))
        self.pushButton.setText(_translate("Dialog", "🔍搜索"))
        self.groupBox.setTitle(_translate("Dialog", "内容显示区"))
        self.groupBox_2.setTitle(_translate("Dialog", "加载进度"))
        self.groupBox_3.setTitle(_translate("Dialog", "时间"))
        self.label.setText(_translate("Dialog", "Year"))
        self.label_2.setText(_translate("Dialog", "Month"))
        self.label_3.setText(_translate("Dialog", "day"))
        self.groupBox_4.setTitle(_translate("Dialog", "简易计算器"))
        self.pushButton_2.setText(_translate("Dialog", "1"))
        self.pushButton_3.setText(_translate("Dialog", "4"))
        self.pushButton_4.setText(_translate("Dialog", "7"))
        self.pushButton_5.setText(_translate("Dialog", "2"))
        self.pushButton_6.setText(_translate("Dialog", "5"))
        self.pushButton_7.setText(_translate("Dialog", "8"))
        self.pushButton_8.setText(_translate("Dialog", "3"))
        self.pushButton_9.setText(_translate("Dialog", "6"))
        self.pushButton_10.setText(_translate("Dialog", "9"))
        self.pushButton_11.setText(_translate("Dialog", "0"))
        self.pushButton_12.setText(_translate("Dialog", "+"))
        self.pushButton_13.setText(_translate("Dialog", "-"))
        self.pushButton_14.setText(_translate("Dialog", "×"))
        self.pushButton_15.setText(_translate("Dialog", "÷"))
        self.pushButton_16.setText(_translate("Dialog", "="))
        self.groupBox_5.setTitle(_translate("Dialog", "小型笔记框"))
        self.pushButton_17.setText(_translate("Dialog", "保存"))
        self.pushButton_18.setText(_translate("Dialog", "打包分享"))
        self.pushButton_19.setText(_translate("Dialog", "清空"))
        self.groupBox_6.setTitle(_translate("Dialog", "检查更新"))
        self.pushButton_20.setText(_translate("Dialog", "检查更新(Official Website)"))
        self.label_4.setText(_translate("Dialog", "   2025 DeepLora™版权所有  VaheStudio汉化支持  Github: github.com/vahestudio DeepLora联系方式: LanJusuntar@markline.dpdns.org .NET制作 软件版本: Alpha 1.0.1"))
        self.groupBox_7.setTitle(_translate("Dialog", "网站工具"))
        self.pushButton_21.setText(_translate("Dialog", "强制刷新"))
        self.pushButton_22.setText(_translate("Dialog", "强制退出"))
        self.pushButton_23.setText(_translate("Dialog", "管理cookie"))
        self.pushButton_24.setText(_translate("Dialog", "主页设置"))


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())